"""
Django settings for DJANGO_PROJECT project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import os.path
from typing import Any  # Add Any for type hinting
import dj_database_url  # Ensure dj_database_url is imported
import cloudinary # Ensure cloudinary is imported

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Define the base directory of the project
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# For production security, get SECRET_KEY from environment variable or use default for dev
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-*v3^895-_e&e*^ud#$4^^=#(x_ta+vd0usks3nr0(qwi@2kiu$')

# SECURITY WARNING: don't run with debug turned on in production!
# In production, set this to False
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

# Allow specific hosts in production or all in development
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [os.environ.get('DJANGO_ALLOWED_HOST', 'blog-it.com'), 'www.blog-it.com', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Add the sites framework
    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_summernote',
    'cloudinary_storage',  # Add cloudinary_storage to all environments
    'cloudinary',  # Add cloudinary to all environments
    # 'mcp_server',  # Add the mcp_server app # Removed as MCP server functionality is being decommissioned
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise middleware for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.DynamicSiteMiddleware',  # Add our custom middleware
]

ROOT_URLCONF = 'DJANGO_PROJECT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # if you have a general templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.popular_tags', # Added popular_tags
                'blog.context_processors.search_form_context', # Added search_form_context
            ],
        },
    },
]

WSGI_APPLICATION = 'DJANGO_PROJECT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database configuration - SQLite locally, PostgreSQL on Render
DATABASES: dict[str, dict[str, Any]] = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Use PostgreSQL in production (on Render)
# Safely handle database URL configuration
if 'DATABASE_URL' in os.environ:
    database_url = os.environ['DATABASE_URL']
    # Check if the URL is for PostgreSQL and adjust SSL mode if necessary
    if database_url.startswith('postgres://') or database_url.startswith('postgresql://'):
        db_url_config = dj_database_url.parse(database_url, ssl_require=True, conn_max_age=600)
    else:
        db_url_config = dj_database_url.parse(database_url)

    DATABASES['default'] = {
        'ENGINE': db_url_config.get('ENGINE', 'django.db.backends.postgresql'),
        'NAME': db_url_config.get('NAME', ''),
        'USER': db_url_config.get('USER', ''),
        'PASSWORD': db_url_config.get('PASSWORD', ''),
        'HOST': db_url_config.get('HOST', ''),
        'PORT': str(db_url_config.get('PORT', '')) if db_url_config.get('PORT') else '',
        'OPTIONS': db_url_config.get('OPTIONS', {}),
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files configuration
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Initialize CLOUDINARY_STORAGE as an empty dict at the module level
# This ensures it exists for django-cloudinary-storage to find.
CLOUDINARY_STORAGE = {}

# Storage configuration for Django 4.0+
# Default storage configuration for development
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# For production media file storage
if not DEBUG:
    # Check for Cloudinary configuration via environment variables
    cloudinary_url = os.environ.get("CLOUDINARY_URL")
    if cloudinary_url:
        # Parse the URL manually to populate CLOUDINARY_STORAGE
        import re
        m = re.match(r"cloudinary://(\w+):(\w+)@([\w\-]+)", cloudinary_url)
        if m:
            # This approach works more reliably than other methods
            CLOUDINARY_STORAGE = {
                "CLOUD_NAME": m.group(3),
                "API_KEY": m.group(1),
                "API_SECRET": m.group(2),
            }
            STORAGES["default"] = {
                "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
            }
            print(f"Cloudinary configured with CLOUD_NAME: {CLOUDINARY_STORAGE['CLOUD_NAME']}")
        else:
            print("CLOUDINARY_URL format invalid! Please check your environment variable.")
    # Alternate method using separate Cloudinary environment variables
    elif (os.environ.get('CLOUDINARY_CLOUD_NAME') and 
          os.environ.get('CLOUDINARY_API_KEY') and 
          os.environ.get('CLOUDINARY_API_SECRET')):
        CLOUDINARY_STORAGE = {
            "CLOUD_NAME": os.environ.get('CLOUDINARY_CLOUD_NAME'),
            "API_KEY": os.environ.get('CLOUDINARY_API_KEY'),
            "API_SECRET": os.environ.get('CLOUDINARY_API_SECRET'),
        }
        STORAGES["default"] = {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        }
        print("Cloudinary configured using individual environment variables.")
    # AWS S3 fallback if Cloudinary isn't configured
    elif 'AWS_ACCESS_KEY_ID' in os.environ:
        # AWS S3 configuration
        AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
        AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
        AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
        AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
        AWS_DEFAULT_ACL = 'public-read'
        
        # Use S3 for media files (Django 4.0+ format)
        STORAGES["default"] = {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        }
    else:
        print("WARNING: No cloud storage configured (CLOUDINARY_URL or AWS not set). Media files won't work in production.")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK='bootstrap5'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
LOGIN_REDIRECT_URL = 'blog-home'
LOGOUT_REDIRECT_URL = '/'  # Redirect to homepage after logout
LOGOUT_RESET_REDIRECT = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
LOGIN_URL = 'login'

# Password reset email settings

# Use Gmail SMTP configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'amswars5559@gmail.com'
EMAIL_HOST_PASSWORD = 'ahml pnif jypf mkie'

# Set the default from email and site name for password reset
DEFAULT_FROM_EMAIL = 'Blog-It <amswars5559@gmail.com>'
SERVER_EMAIL = 'amswars5559@gmail.com'  # Server error emails
EMAIL_SUBJECT_PREFIX = '[Blog-It] '

# Site ID for the sites framework
SITE_ID = 1

# For development, override the site domain to use localhost
if DEBUG:
    SITE_URL = 'http://127.0.0.1:8000'
    DOMAIN_NAME = '127.0.0.1:8000'
else:
    # Production settings for Render
    SITE_URL = f"https://{os.environ.get('DJANGO_ALLOWED_HOST', 'blog-app.onrender.com')}"
    DOMAIN_NAME = os.environ.get('DJANGO_ALLOWED_HOST', 'blog-app.onrender.com')

SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'width': '100%',
        'height': '480px',  # Increased height for better editing experience
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
        'fontNames': ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Helvetica', 'Impact', 'Tahoma', 'Times New Roman', 'Verdana'],
        'callbacks': {
            'onInit': """
                function() {
                    console.log('Summernote initialized');
                }
            """,
        },
    },
    'css': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
        '/static/css/summernote-custom.css',  # Include our custom CSS
    ),
    'codemirror': {
        'theme': 'monokai',
        'mode': 'htmlmixed',
        'lineNumbers': True,
        'lineWrapping': True,
    },
}

# Add the MCP server URL
# MCP_SERVER_URL = 'http://localhost:8080' # Removed as MCP server functionality is being decommissioned

# Security settings for production
if not DEBUG:
    # HTTPS/SSL settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Content security
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
